### ISSUE TITLE
Upload to Maven

### ISSUE THREAD

**Issue by dustalov** [utir/square#5]
It would be great if SQUARE will be published on Maven Central. Are you planning doing this? At the present moment, I have to use this library via [JitPack](https://jitpack.io/), which requires declaring additional repository in my `pom.xml`.

* <http://search.maven.org/>
* <https://maven.apache.org/guides/mini/guide-central-repository-upload.html>
* <http://central.sonatype.org/pages/apache-maven.html>

However, it will require some modifications in the source code. Firstly, it will be necessary to change the package name to something like `edu.utexas.school.ir.square`, which is not an issue. Secondly, the project's `pom.xml` should be modified to use, for instance, the hosting provided by Sonatype.

**Comment by aashish-sheshadri** [comment]
Thats a good idea, thanks Dmitry -- I need two weeks, I have been working
on another version of SQUARE were unsupervised estimation can be done on
100% of the dataset. I also have a framework where good simulation data can
be generated.

I have been swamped recently and haven't been able to work on it -- I am
trying my best to push the new version out and can, as you have
recommended, push it to Maven Central.

On Sun, Oct 11, 2015 at 8:24 AM, Dmitry Ustalov <notifications@github.com>
wrote:

> It would be great if SQUARE will be published on Maven Central. Are you
> planning doing this? At the present moment, I have to use this repository
> via JitPack <https://jitpack.io/>, which requires declaring additional
> repository in my pom.xml.
>
>    - http://search.maven.org/
>    -
>    https://maven.apache.org/guides/mini/guide-central-repository-upload.html
>    - http://central.sonatype.org/pages/apache-maven.html
>
> However, it will require some modifications in the source code. Firstly,
> it will be necessary to change the package name to something like
> edu.utexas.school.ir.square, which is not an issue. Secondly, the
> project's pom.xml should be modified to use, for instance, the hosting
> provided by Sonatype.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/utir/square/issues/5>.
>



-- 
-Aashish

**Comment by aashish-sheshadri** [comment]
Version 2.0 uploaded -- will wait for a bit to check on issues before pushing to maven central.

**Comment by dustalov** [comment]
It is great! Why did you use another repository instead of contribution to the present one?
