### ISSUE TITLE
Why didn't I see the implementation of the GLAD and DS algorithm in the square/src/main/java/org/square/qa/algorithms/ folder

### ISSUE THREAD

**Issue by tongrenypj** [utir/square#6]

**Comment by tongrenypj** [comment]
Sorry！Why didn't I see the implementation of the GLAD and DS algorithm in the square/src/main/java/org/square/qa/algorithms/ folder

**Comment by aashish-sheshadri** [comment]
@tongrenypj Implementation of GLAD and DS algorithms were made available by authors.
Only algorithms for which implementations weren't readily available were implemented.
